spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: davilucciola
    password: postgres
    url: jdbc:postgresql://127.0.0.1:5432/softfinance
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql